### ISSUE TITLE
Crashing when opening inventory with filled cauldron backpack

### ISSUE THREAD

**Issue by Delfonso** [BeansGalaxy/Beans-Backpacks-2#102]
If I empty the cauldron backpack before opening the inventory the game doesn't crash.

mod vercion: 0.20 v2

**Comment by BeansGalaxy** [comment]
do you have a crash report?

**Comment by BeansGalaxy** [comment]
or post a download of your latest.log. You can find it in `.minecraft/logs`

**Comment by Delfonso** [comment]
here is the crash report: [crash-2024-03-23_22.04.55-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14748216/crash-2024-03-23_22.04.55-client.txt)

**Comment by BeansGalaxy** [comment]
Oops I was trying to access a class that's only present during development. This'll be fixed in 20.1-0.21-v2

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.22-v2 :)
