### ISSUE TITLE
Backpack dupes filling almost every trinket slot (especially with Not Enough Trinket Slots installed)

### ISSUE THREAD

**Issue by Dumpling00** [BeansGalaxy/Beans-Backpacks-2#106]
This only seems to happen in Creative mode, I get one backpack, I end up with a dozen.
Seems very easy to replicate, happens pretty much all the time. Is it possible for this to be looked into?

**Comment by BeansGalaxy** [comment]
Oops I'll check it out. 

I disabled creative mode a while ago in development since it's pretty complicated for adding only adding a scroll bar and infinite items. Recently I re-added support for it since I'm pushing for a full release next month so creative might be a little iffy until then.

**Comment by BeansGalaxy** [comment]
Solved in the 20.1-0.22-v2. Thanks for the report!

Both the survival and creative inventories have a list of slots but the slot I add came before the trinkets slots in survival and after in creative. So when equipping the backpack it would place it in the slot you clicked, then would get synced from the server to the slot next to it in the list.
