### ISSUE TITLE
Item Blacklist

### ISSUE THREAD

**Issue by Dumpling00** [BeansGalaxy/Beans-Backpacks-2#107]
Hi! Love the mod, I am using it in tandem with other inventory-enhancing mods, such as Travellers' Backpacks, and I was wondering if we could get a config to blacklist certain items in order to prevent them from being stored in the backpack. (like in this case bags from other mods to avoid inception-stacking)

Thank you for your time and consideration!

**Comment by BeansGalaxy** [comment]
Yeah so you can already add this if you know how to use data-packs. Here's the [wiki page](https://github.com/BeansGalaxy/Beans-Backpacks-2/wiki/Configurations). Read through Item Lists and check out `blacklist_items`. Attached is a .zip of a data pack you can use to start with.

[Modify Data Template.zip](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14794942/Modify.Data.Template.zip)
