### ISSUE TITLE
backpacks duping on a server when having the back slot filled (with curios installed)

### ISSUE THREAD

**Issue by dxcvvxd** [BeansGalaxy/Beans-Backpacks-2#109]
so i dont know the exact reason why this happens and i dont have access to logs of the server but when i have my back slot filled or even if its empty and i have a backtank from create, the backpack just dupes and i can place it infinetly with all the items untill it kicks me from the server and i cant connect anymore due to playerdata not loading.
this is really easy to reproduce, just have your back slot or chestplate slot filled with something other than standart minecraft armor.

**Comment by BeansGalaxy** [comment]
upload your client's log file when you tried to reconnect to the server. What ever the issue that causes you to fail to reconnect will spit out some info there that can help me diagnose.

**Comment by BeansGalaxy** [comment]
So equipping create's backtank should be disabled with a backpack on, and it is on the server but not on the client. A list of items that disable the back slot is created when data packs are loaded and the server never sends that list to the client. So when you put on the backpack, the client and server desync and cause errors.

Keep a lookout for 20.1-0.22-v2. I'll have it fixed there.
