### ISSUE TITLE
Curios Mod Incompatiblity

### ISSUE THREAD

**Issue by AlexModGuy** [BeansGalaxy/Beans-Backpacks-2#118]
with the Curios mod installed, trying to shift-click backpacks in the inventory technically equips them. but as soon as the curios tab is opened in the inventory, the backpacks are deleted. There is also no backpack slot with curios installed.

I would recommend checking out how The Aether added a config option to allow it's necklaces and gloves etc to use curio slots without making curios a requirement.

**Comment by AlexModGuy** [comment]
![2024-04-10_08 13 04](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/8662109/e4533fa4-ca55-4cb7-bc2c-92479bd048ac)
it looks like this too

**Comment by BeansGalaxy** [comment]
Dang you can tell it's broken just by looking at it. I must've broken it when I added the help menu. I'll check out what's doing this. Btw Curios isn't a requirement for Beans Backpacks, if my mod detects if Curios or Trinkets are installed it automatically switches to using them but you don't need either installed for my mod.

**Comment by BeansGalaxy** [comment]
I can only re-create the bug where the backpack gets deleted when equipping it in creative mode. I also don't have a problem with the Back Slot not appearing though so it might be another mod you have installed. Also I can't re-create the menu looking broken like that. 

What mods do you have installed that alter the inventory. I can see that the off-hand slot is moved and there's a sort button. What are those mods and do you have any other mods like that installed? I could try to recreate the bug with those mods installed. I already tested with JEI

**Comment by BeansGalaxy** [comment]
I've solved the issue causing elytra not to deploy correctly, I plan to release the update tmrw but I am curious what you did to get the help menu to look like that. I've tried with Curios and JEI installed and those seem to work fine so I'm unsure how else to diagnose this. LMK!! :)
