### ISSUE TITLE
suggestion: add a way to toggle being able to put an elytra in the backpack slot in the config

### ISSUE THREAD

**Issue by Briarbot2011** [BeansGalaxy/Beans-Backpacks-2#122]
i don't want to be able to wear both an elytra and a chestplate at the same time on my private modpack, but i do want to be able to wear a backpack with an elytra.

**Comment by BeansGalaxy** [comment]
You can already do this through data packs. Follow along with [Data Configurations](https://github.com/BeansGalaxy/Beans-Backpacks-2/wiki/Configurations#data-configurations) and add `!minecraft:elytra` to the elytra_items list. This was my solution before I added config and I plan to add these features but in the meantime use this with a mod that lets you add global data packs.

**Comment by BeansGalaxy** [comment]
20.1-0.28-v2 has moved "Data Configurations" into config. Now you can remove the elytra from `elytra_items` without needing a data pack :) about time right?
