### ISSUE TITLE
Crash with Cauldron if (modded) block does not have `waterlogged` Property

### ISSUE THREAD

**Issue by Red3Tango** [BeansGalaxy/Beans-Backpacks-2#126]
Versions:
Minecraft - 1.20.1
BeansBackpacks - forge-1.20.1-0.24-v2.jar
Forge - 47.2.23

When Ctrl+Clicking on a modded block (Terrafirmacraft) that does not have a property for `waterlogged`, will cause game/server to crash. With Terrafirmacraft the ability to pickup/place water blocks is extremely limited to late-game (requires specific items). With Backpacks it works without issue, as long as the target block does not contain any of the TFC modded blocks.

Having a `.json` config file to disable putting the Cauldron on your back that could be overwritten in a datapack would be extremely helpful, especially for TFC.

> The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{tfc:rock/loose/andesite}

[crash-2024-04-18_23.41.55-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15033649/crash-2024-04-18_23.41.55-client.txt)

**Comment by BeansGalaxy** [comment]
I'll add an option in the next update. Super cool to see terrafirmacraft updated again, used to ***love*** that mod. Can't wait for someone to get it balanced & working with Create

**Comment by BeansGalaxy** [comment]
20.1-0.25-v2 on Modrinth lets you change the max_stacks of Pots and Cauldrons to 0 which disables them.

**Comment by Red3Tango** [comment]
Thanks, already tested and works nicely! Fits much better with TFC now, as you can no longer move source blocks with buckets, it requires making pumps!
