### ISSUE TITLE
Can't equip backpack until all other trinket slots are empty!

### ISSUE THREAD

**Issue by DarkFighter5000** [BeansGalaxy/Beans-Backpacks-2#129]
Using the Trinkets mod (trinkets-3.7.2) with Jewelry (RPG Series) mod (Jewelry-1.3.0+1.20.1) I can't equip the backpack unless I remove my chestplate, ring and necklace; It says "[Air] and [Air] is already equipped". After I do that and equip the backpack I can however reequip everything else and the backpack works just fine.

Game
1.20.1 Fabric - 0.15.10

Mod Version
BeansBackpacks-fabric-1.20.1-0.24-v2

**Comment by BeansGalaxy** [comment]
Oops, I have a pipeline that lets other mod/mod pack creators flag items that cant be worn with the backpack and it looks like there's some air in the pipes. I'll add a check to ignore any Air items.

I made this data pack that should solve the problem until the update is out
[Air Valve for Beans Backpacks.zip](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15055279/Air.Valve.for.Beans.Backpacks.zip)

**Comment by DarkFighter5000** [comment]
> Oops, I have a pipeline that lets other mod/mod pack creators flag items that cant be worn with the backpack and it looks like there's some air in the pipes. I'll add a check to ignore any Air items.
> 
> I made this data pack that should solve the problem until the update is out [Air Valve for Beans Backpacks.zip](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15055279/Air.Valve.for.Beans.Backpacks.zip)

**Comment by DarkFighter5000** [comment]
Cool thanks! Best of luck with your work!

**Comment by BeansGalaxy** [comment]
No problem! I'm gonna keep this issue open until I release the update just incase anyone else runs into this problem

**Comment by BeansGalaxy** [comment]
I Couldn't re-create the issue but I added some redundant checks to make sure Air doesn't disable the Back Slot. Should be fixed in 20.1-0.25-v2, latest version is only on Modrinth for now.
