### ISSUE TITLE
Crash and JEI bug

### ISSUE THREAD

**Issue by NoQOL** [BeansGalaxy/Beans-Backpacks-2#13]
Minecraft Version - 1.20.1
Forge Version - 47.2.19
Mod Version - Forge v2-0.0

I was playing in my personal modpack and the game crashed when i broke a chest with items inside.

[crash-2024-01-12_02.12.25-server.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13915283/crash-2024-01-12_02.12.25-server.txt)

Also, when i have the mod installed it messes up with JEI and it doesn't show normal crafting recipes when i press U, but for some reason it does show create deployer recipes.

**Comment by MarbleHoarder** [comment]
I had a similar JEI issue but on fabric (mod version v2-0.0_20.1), try downgrading to a previous version for now.

**Comment by BeansGalaxy** [comment]
JEI is fixed. Also it looked like the game crashed due to the mod trying to add items to a backpack that wasn't equipped, That's also fixed in v2-0.1
