### ISSUE TITLE
Backpack duplication glitch

### ISSUE THREAD

**Issue by VitaminJake** [BeansGalaxy/Beans-Backpacks-2#133]
It's possible to reliably duplicate backpacks due to shift clicking. When you're dying a backpack (we were using winged backpack specifically), if you put the backpack in the inventory crafting grid with a dye, then shift-click it out, it duplicates it. It auto-equips one onto your character, and leaves one in the crafting grid.

It only lets me post a 10mb video, so I have to cut the portion where I show it, but there is another one in my backpack slot.

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/162518177/b2ac30f7-2eb5-4b60-9cd7-3c2032b90791

**Comment by VitaminJake** [comment]
Tested with versions 0.25, 0.24, and 0.23 for possible workarounds, occurred in all three

**Comment by BeansGalaxy** [comment]
In your inventory if you shift click any slot it checks if you can equip that item to the back. I guess I never check if it's the crafting output. I'll add one so this won't happen in the next update.

Btw that armor's cool what mod is that?

**Comment by VitaminJake** [comment]
It's the arcane armour from the Wizards (RPG Series) mod by [ZsoltMolnarrr] (https://modrinth.com/user/ZsoltMolnarrr) 
Highly recommend his work.

**Comment by BeansGalaxy** [comment]
Solved in 20.1-0.26-v2! Thanks for the report :)

**Comment by VitaminJake** [comment]
Yuuuuuuuuge fixes, thank you kindly Mr Bean
