### ISSUE TITLE
[Fabric 1.20.1] Unequippable Backpack Slot

### ISSUE THREAD

**Issue by icenii** [BeansGalaxy/Beans-Backpacks-2#134]
It works perfectly fine at Singleplayer however, at multiplayer, the backpacks cannot be equipped.

**Comment by BeansGalaxy** [comment]
do you have any other mods installed or any armor equipped?

**Comment by Sylphily** [comment]
I have had the same problem too, but with #132, i wouldn't be able to send any logs related, but i can share my mod list, 1.20.1 Fabric


![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/30062054/e1e42b5f-82e2-446e-b10f-f48f0c12016d)

**Comment by BeansGalaxy** [comment]
In the newest version 20.1-0.26-v2, I added notifications whenever the back slot is preventing items from being equipped. Elytra's and Backpacks cannot be work together so now there should be a notification whenever you try to equip something that can't. Lmk if you still have this issue and if any message appears in your inventory.

**Comment by BeansGalaxy** [comment]
I've made a lot of changes to items disabling the back slot and I think the mentioned issue is the same one here so I'm closing this issue. Feel free to open this back up if you run into this problem again :)
