### ISSUE TITLE
Mod Menu error

### ISSUE THREAD

**Issue by Fukuyarieru** [BeansGalaxy/Beans-Backpacks-2#137]
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/121601030/6f4cf58c-85d1-4acd-97ff-0a32cf893b97)

fabric 1.15,10
Minecraft 1.20.1
beans backpack 20.1 - 0.26-v2

**Comment by BeansGalaxy** [comment]
The config has been completely re-done in *I think* 20.1-0.24-v2.  I haven't re-made a menu for it yet but you can still edit the config through the config folder in .minecraft. I have a few more config options I want to add before I start making the screen.

**Comment by BeansGalaxy** [comment]
Added a new config menu in 20.1-0.30-v2 :)
