### ISSUE TITLE
Configuration files changed

### ISSUE THREAD

**Issue by Red3Tango** [BeansGalaxy/Beans-Backpacks-2#138]
noticed after updating from 0.24 → 0.26 (and 0.27) using forge it now creates these config files

beansbackpacks-client.json5
beansbackpacks-common.json5

however, the wiki still states they are .toml files... which ended up messing things up on my server as it did not use the settings in the previous .toml files but the new .json5 ones.

**Comment by BeansGalaxy** [comment]
Sorry for that, I'll update the wiki to be about the new .json5 format

**Comment by Red3Tango** [comment]
thankfully we were re-rolling to a new seed when i caught the issue, so corrupted data and missing items didnt matter lol.
