### ISSUE TITLE
Closes the modpack when accessing

### ISSUE THREAD

**Issue by xxdemiigod** [BeansGalaxy/Beans-Backpacks-2#140]
For some reason, whenever I enter the backpack, then select something to put into my inventory, my game automatically closes. I haven't changed any of the default configs, and it's not crashing because there is no crash report and it doesn't register as a crash in the console. The game just closes. This makes the mod practically unusable because my game keeps closing each time I try to enter my backpack.

**Comment by xxdemiigod** [comment]
The mod also seems to work just fine in creative mode without issues, but if I try to select anything from the backpack in Survival mode, the game closes.

**Comment by BeansGalaxy** [comment]
This is super weird... Are you using an ender backpack? I just made a lot of changes to them so maybe I accidently close the game instead of the screen? Also maybe you're logs have a clue as to what happening, you can find them in `.minecraft/log` or where ever your modpack is there should be a `log` folder.

**Comment by BeansGalaxy** [comment]
Hit the paper clip icon and attach the log if you find it

**Comment by xxdemiigod** [comment]
[latest (3).log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15265020/latest.3.log)

I believe this is the log that contains all the disconnects. I also added a screenshot of all the mods I have installed too.

![Screenshot 2024-05-09 125557](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/99450721/05f6e1f9-8fc3-4b3c-8c7a-95c030782c88)

**Comment by xxdemiigod** [comment]
I also uploaded a short video of the closing for you.
https://www.youtube.com/watch?v=ioquw7Y1bXA

**Comment by BeansGalaxy** [comment]
So I couldn't recreate the bug but the crash report led straight to some unstable code that I cleaned up and hopefully it should be fixed. The crash was happening when the backpack slots were reorganized so, currently I update the slots every frame, now I only update them when the player clicks, Hopefully this won't be an issue in the next update

**Comment by BeansGalaxy** [comment]
1.20.1-0.28-v2 is out with some clean up to where the problem is occurring. I'm pretty sure I solved the issue but if you still run into it don't be afraid to re-open this issue
