### ISSUE TITLE
Backpack simply disappears after a non-specific amount of time. only for users with capes on their skin.

### ISSUE THREAD

**Issue by LadyStrella** [BeansGalaxy/Beans-Backpacks-2#146]
I really cant find anything helpful on my logs, but from my testing it seems to related to the cape roll up feature.
the items dont get deleted, i could still take them off using the special slot on the bottom of the character display so realistically the only thing we kept losing is some leather and string. it seems to only be happening to the players with capes, and so far, simply disabling the cape on the skin settings seem to prevent it from despawning, its specially odd since it doesnt disappear immediately so im not sure if something specific is triggering the issue.

**Comment by LadyStrella** [comment]
update, turning off the cape on the skin settings still make the backpack disappear

**Comment by BeansGalaxy** [comment]
I can't seem to replicate it on my system so some quick questions, if you don't know something then don't worry about answering it. This is just my brain going off on everything that might narrow down the cause. Didn't mean to turn this into a pop quiz...

1. Is Curios/Trinkets installed?
2. Fabric or Forge
3. Singleplayer, Lan, or Server?
4. How's your day going?
5. Is the item in the Back Slot is gone?
6. Can you still see the Backpack on the player's back?
7. If you have no backpack do you see your cape?
8. Does it happen when you...
  a. use the hotkey to equip it
  b. equip it through your inventory
  c. randomly
9. Do you have any more steps I could take to reproduce this?

**Comment by LadyStrella** [comment]
1. yes i have curious trinkets installed, and another mod that adds a backslot for the elytra called "elytra slot" tho at the current time no one on the server has an elytra yet.
2. Fabric
3. Dedicated server
4. Pretty good thank you c:
5. The item disapears and i really cant pinpoint when, i'll just open my inventory and its gone, i tried teleporting all placed backpacks to me to see if i placed it by accident and nothing teleported. so im sure it wasnt placed, unless it despawned somehow.
6. we can but not after its gone, relogging from the sever doesnt help either.
7. if i have the backpack my cape folds on top of it, it looks rather neat, its a lovely touch ^^
8. c. i will open my inventory some times and it is just not there anymore, it even lets me equip another backpack, thankfully the items inside dont disappear and i can just drop them through the slot on the inventory.
9. im really not sure what else could be causing it, i have supplementaries installed, and create mod if that's any help, i dont have any mod that changes inventory besides trinkets, i also changed the config to use the integrated backpack display and have all backpacks able to hold 8 stacks since i like the looks of the leather backpack.

thank you for the mod btw, its by far my favorite backpacking solution c:

**Comment by BeansGalaxy** [comment]
Shift clicking ANY empty slot in the inventory will delete the backpack. 🤦 Oops.. No clue what's causing this but I'll keep you updated when I have a fix.

**Comment by BeansGalaxy** [comment]
20.1-0.29-v2 is out with the fix! Enjoy :D
