### ISSUE TITLE
Wearing stacked cauldrons when shift-clicking inside inventory

### ISSUE THREAD

**Issue by Fukuyarieru** [BeansGalaxy/Beans-Backpacks-2#147]
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/121601030/cc2ffdfc-8067-40d0-824c-ff3c71fdbcf6)

I tried it a bit and it doesn't seem to do much, other than the fact of having multiple cauldrons worn at the same time.
there weren't any bugs with getting or putting water

**Comment by Fukuyarieru** [comment]
gif seems to be broken: https://imgur.com/5UV2J17

**Comment by Fukuyarieru** [comment]
forgot to mention: this is the latest version of the mod, Minecraft 1.20.1, and the latest fabric version

**Comment by BeansGalaxy** [comment]
Oops, literally just have to change a number in the code. It'll be fixed in the next update. Thanks for the gif too! ;)

**Comment by BeansGalaxy** [comment]
I didn't get around to fixing this in 20.1-0.30-v2 but it's fixed when the next one is released

**Comment by BeansGalaxy** [comment]
Solved in 20.1-2.0
