### ISSUE TITLE
Backpack randomly disappears when swapping armor

### ISSUE THREAD

**Issue by FumpleWumper** [BeansGalaxy/Beans-Backpacks-2#148]
I am playing on Fabric 0.15.10, Minecraft 1.20.1, and using Bean's Backpacks 0.29 v2.

I've found and been able to succesfully recreate a bug that causes the backpack to completely disappear, by putting the backpack in its backpack slot and then putting on and taking off armor, below is a link of me recording it.

https://medal.tv/games/minecraft/clips/2dQ45SsFIvpHUE/d1337SrZPQxv?invite=cr-MSxla0ssMTk5NjA5MTU2LA

**Comment by BeansGalaxy** [comment]
I can't replicate this on my system. There was a bug that was equipping empty slots but I fixed it in 0.29-v2. For my sanity double check you're in that version. Maybe delete the mod, get a fresh download, and try it again? (With a leather backpack this time)

Other than that you can try to replicate that old bug and see if it's slipping through some how still. The old bug deleted the backpack when you would shift click any empty slot in the inventory. If you have some extra leather & string, test it out and let me know if it's still happening.

**Comment by FumpleWumper** [comment]
Ah I found the issue, even though on my client I had 0.29, my server was still running 0.28 and letting the bug happen, sorry for the random report :,D

**Comment by BeansGalaxy** [comment]
Gotcha! Thanks for the report anyways, I appreciate the help :)))
