### ISSUE TITLE
ui conflict with cosmetic armor reworked mod

### ISSUE THREAD

**Issue by GauntAndreX8** [BeansGalaxy/Beans-Backpacks-2#149]
![2024-05-17_16 58 49](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/85809443/51be5cd5-a86d-4872-bed5-279afb4d4f07)

**Comment by BeansGalaxy** [comment]
When I get around to creating a config screen I was going to add a setting to move the back slot around. I'll have a config setting in the next update but you'll have to guess & check with coordinates but it'll be possible

**Comment by BeansGalaxy** [comment]
I decided to go ahead and make a config screen in 20.1-0.30-v2. Look for `back_slot_pos` and you'll find an edit button to move the back slot around. This is a server sided setting btw so let any admins know if you need to :)
