### ISSUE TITLE
Issues with (apparently) Sinytra Connector and Trinkets API

### ISSUE THREAD

**Issue by masmasmas66** [BeansGalaxy/Beans-Backpacks-2#15]
While this issue doesn't occur solely with the Connector and Trinkets API, when another mod (such as Supplementaries) adds trinket slots, everything breaks.
Respawn functionality becomes non-responsive (the button doesn't work), or the game may crash outright.
 

[crash-2024-01-13_13.53.09-server.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13928903/crash-2024-01-13_13.53.09-server.txt)
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13928905/latest.log)

**Comment by BeansGalaxy** [comment]
Trinkets and Curios currently doesn't work with my mod. I'm looking to a fix but for now they just aren't compatible.

**Comment by BeansGalaxy** [comment]
PS; Is there a reason you're using Connector over using my forge release?

**Comment by BeansGalaxy** [comment]
Added Support for Curios and Trinkets in v2-0.8 for 1.20.2. I'll be porting to 1.20.1 soon. Avoid using Connector since I have support for both versions.
