### ISSUE TITLE
You can ignore the armor bans (while winged-back'd) by just hovering and replacing the armor on the armor slot.

### ISSUE THREAD

**Issue by Jous4n** [BeansGalaxy/Beans-Backpacks-2#153]
https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/118950641/5635dae0-2e19-4102-9495-52e3b5c1d596

**Comment by BeansGalaxy** [comment]
Solved in the next update, thanks for bringing this to me :))

**Comment by Jous4n** [comment]
> Solved in the next update, thanks for bringing this to me :))

Awesome!!! Thanks for solving it!

**Comment by Jous4n** [comment]
Congrats on moving from beta to release btw!
