### ISSUE TITLE
Crash when you put modded liquid in cauldron in curious slot

### ISSUE THREAD

**Issue by damikdevil** [BeansGalaxy/Beans-Backpacks-2#156]
game crashes when you put modded liquid in cauldron in curious slot (for example alexs caves toxic liquid bucket)
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15481765/latest.log)
[crash-2024-05-29_13.59.06-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/15481769/crash-2024-05-29_13.59.06-client.txt)

**Comment by BeansGalaxy** [comment]
It looks like the fluid doesn't have a place sound where I expected it to be. I'll see if I can ignore the sound entirely if I don't find one.

**Comment by BeansGalaxy** [comment]
The issue also crashed the game if it couldn't find a texture for the liquid. I plan on ripping out the cauldron code at one point but until then it just skips rendering it when hovering or on the back if there is no texture. Fixed in v20.1-2.0.2
