### ISSUE TITLE
Winged Backpacks don't repair themselves with Mending

### ISSUE THREAD

**Issue by FumpleWumper** [BeansGalaxy/Beans-Backpacks-2#159]
As the title says, even when you enchant a Winged Backpack with Mending, receiving experience won't actually repair it as long as it is in your dedicated backpack slot, only if you hold it in your hand.

I am playing on Minecraft 1.20.1, Fabric 0.15.10, and Beans Backpacks 2.0

**Comment by BeansGalaxy** [comment]
The Mending enchantment works by stepping through both hands then each pre-determined armor slot and there's no way for me to jump in there. I could've sworn I've added a line a code that randomly chooses the back slot whenever mending tries to repair but in my world I ran into the same issue. 

Currently racing the release of 1.21 to try to be the first backpack mod when it's released, so there might be a little time before I get out a fix

**Comment by FumpleWumper** [comment]
That's valid, I hope that gets more eyes on the mod!! 
Thankfully in my server everyone noticed that Mending wasn't working before blindly letting the backpacks break so it wasn't so bad, but the fix would help so that we don't have to anxiously check on the backpack every once in a while X,D

**Comment by BeansGalaxy** [comment]
Turns out the bug was only repairing the backpack if another armor had mending and was also damaged so kinda funky behavior. Fixed in v2.0.1
