### ISSUE TITLE
Enhancement: Rebind controls

### ISSUE THREAD

**Issue by CoruscareGames** [BeansGalaxy/Beans-Backpacks-2#162]
I use tab to shift. Being unable to change the shift+right click to place backpack has lost me my netherite smithing templates, and I would like to prevent this in the future by changing the button I press to place the backpack in the world.

**Comment by BeansGalaxy** [comment]
In the vanilla Key Bind options you can change the controls for the placing/pick up and to quickly move items in the inventory. Also in the client config you could enable `instant_place` to immediately place the backpack without using right click fyi, that might make your situation worse tho.

**Comment by CoruscareGames** [comment]
I don't see the option in the keybind menu, what's it called?

**Comment by BeansGalaxy** [comment]
Scroll down until you see Bean's Backpacks and then it's called "Place/Pickup". Quick Click changes the hot key in the menus
