### ISSUE TITLE
Game crashes when extracting liquid from an empty back cauldron

### ISSUE THREAD

**Issue by Paz-bit** [BeansGalaxy/Beans-Backpacks-2#164]
When holding an empty bucket in inventory, trying to extract liquid from a cauldron backpack with no liquid in it will result in a crash. The following line is returned in crash report.

java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null

The world also can't be opened afterward, returning the same message after the game crashes.
[Forge, 1.20.1]

**Comment by Corcustos** [comment]
The same thing is happening to a player of mine of my server, but it appears the error is slightly different from above. I am also on Fabric 1.20.1, not Forge. Here is the full client log: https://mclo.gs/jqsx1LL

**Comment by BeansGalaxy** [comment]
Yeah you run into this bug while picking up a cauldron that isn't completely full of water. It's an issue with the game trying to render the fluid after it stores it in an incorrect state. I've been working on a 1.21 port currently and I've re-done the cauldron/fluid storage so it's much more reliable. 1.20.1 version is currently in shambles while working on 1.21 but I'll hopefully get to a point where I can get a alpha/beta of 1.21 out and revisit 20.1 soon :)

**Comment by BeansGalaxy** [comment]
Fixed in v2.0.1 ;)
