### ISSUE TITLE
Create Compatability Request: Backtanks

### ISSUE THREAD

**Issue by FumpleWumper** [BeansGalaxy/Beans-Backpacks-2#166]
The Create mod adds tanks of pressurized air that you can carry on your back to either fuel air-based weapons or to give you oxygen while diving.
They come in a Copper and a Netherite variant, and they're both completely identic to armor, they can both be enchanted, and the Netherite variant even grants you the same stats a Netherite Chestplate would but... me and my friends play in a server with upgrades beyond Netherite, where we can get buffs from wearing the full set.

It would be quite useful if we could wear the backtanks on our backpack slot, but without getting any of the defensive stats we'd usually get from wearing them on our chest, hence I'm leaving this suggestion here <:)

I don't know how doable this even is in terms of coding it, but it would be really convenient anyway! Thanks for reading, and I hope the 1.20.6 update is going well o/

**Comment by FumpleWumper** [comment]
Something I forgot to mention - the Netherite Backtank specifically comes with a full piece of armor attached to it, in my suggestion I meant to ask if it was possible to have JUST the tank appear when it's equipped on the back

**Comment by BeansGalaxy** [comment]
Originally I planned to add support for this but it was much more complicated than I originally thought. I likely won't get around to adding this but keep in mind this idea is on the back back burner and I would really like to figure it out one day
