### ISSUE TITLE
Custom backpack not honoring button texture

### ISSUE THREAD

**Issue by JuceInUse** [BeansGalaxy/Beans-Backpacks-2#169]
I have attempted to make a handful of custom backpacks and I defined each of them with a custom button. However, all of them seem to choose the default diamond button texture regardless

![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/85078618/16c55725-eb38-46cb-9344-e48b030a53b0)
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/85078618/fbae53aa-26c9-43c2-94ee-411fa75e1172)

**Comment by BeansGalaxy** [comment]
The `button_material` needs to be written like `minecraft:amethyst`. Try that out and it should work. 

> btw you've really didn't need to cook so hard with that diamond texture
