### ISSUE TITLE
[Crash] Game has crashed with beansbackpacks and other mods

### ISSUE THREAD

**Issue by DrLeonardo95** [BeansGalaxy/Beans-Backpacks-2#17]
Could not execute entrypoint stage.

[beans_crash.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13930912/beans_crash.txt)

**Mod version:** 0.7-v2
**Fabric API:** 0.91.0
**Fabric Loader:** 0.15.3

**Comment by BeansGalaxy** [comment]
From what I can see, the crash report points to a problem with the Additional Redstone mod causing the other mods not to load. Try the modpack without that or try with a different version. Hopefully it should work :)

**Comment by DrLeonardo95** [comment]
> From what I can see, the crash report points to a problem with the Additional Redstone mod causing the other mods not to load. Try the modpack without that or try with a different version. Hopefully it should work :)

I also thought that the problem was in the modification Additional Redstone.

But when installing the latest version of the modification BeansBackpacks, the client crashes with this error. If you install your mod version 1.* - there won't be any problems

The problem occurs after installing the mod version 0.7-v2

**Comment by BeansGalaxy** [comment]
I couldn't say what the problem is from the crash report alone, I'll have to do some testing and get back to this issue.

**Comment by BeansGalaxy** [comment]
It was an Issue with "bettersmithingtable". I was breaking his mod by trying using unsafe injects into minecraft's vanilla code. I fixed the crash and added support for his smithing screen in 20.1-0.4-v2 & 20.2-0.10-v2
