### ISSUE TITLE
Async entity load Crash

### ISSUE THREAD

**Issue by yunus-cakir** [BeansGalaxy/Beans-Backpacks-2#170]
Hi! We are getting a crash when we tried to pick up our bag! And if we re-join to server and try, its starting to jumping and then crashing! Is it possible because of the mod HTM?
- 1.20.1 Fabric
- https://modrinth.com/modpack/valley/version/2.0.1

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/83448525/47eff9ee-bb6f-404f-8ef3-231848a7a8fc

**Comment by BeansGalaxy** [comment]
The `entity.beansbackpacks.locked.is_removed` means the backpack *for some reason* was told to be removed from the world but wasn't killed. If you're only having issues when restarting the server I would look into any mods that might alter entities loading like maybe performance mods.

**Comment by yunus-cakir** [comment]
> The `entity.beansbackpacks.locked.is_removed` means the backpack _for some reason_ was told to be removed from the world but wasn't killed. If you're only having issues when restarting the server I would look into any mods that might alter entities loading like maybe performance mods.

Hi! We're not restarting the server and this the pack that we use. Could you check if you have the time please? I would really appreciate if you could help me because other backpack mods are not really nice.
https://modrinth.com/modpack/valley
https://modrinth.com/modpack/valley/version/2.0.2

**Comment by BeansGalaxy** [comment]
The issue is between the `instant_place` client config option and Concurrent Chunk Management Engine. Disabling instant place or removing C2ME fixes the crash. I've been dismantling the 1.20.1 version to update it to 1.21 so putting it back together and updating it will take a few days. I'll keep you updated on any progress :)

**Comment by yunus-cakir** [comment]
> The issue is between the `instant_place` client config option and Concurrent Chunk Management Engine. Disabling instant place or removing C2ME fixes the crash. I've been dismantling the 1.20.1 version to update it to 1.21 so putting it back together and updating it will take a few days. I'll keep you updated on any progress :)

Thanks I'll wait! :)

**Comment by BeansGalaxy** [comment]
Skill issue when I first set up networking with my mod. After all this time there was never an issue so it's gone unnoticed. I'll get v2.1 out after a little testing.

**Comment by BeansGalaxy** [comment]
v2.0.1 is out with a fix :)
