### ISSUE TITLE
Cauldron backpack causes server to crash when trying to pick up water

### ISSUE THREAD

**Issue by DR0LL1N** [BeansGalaxy/Beans-Backpacks-2#172]
At first i thought it might be some incompatibility between mods, but even with only this mod and fabric api in the mods folders of client and server, the server still crashes when trying to pick up water with bare hand and cauldron equipped in backpack slot.
No such issue in singleplayer.
[crash-2024-06-25_14.41.47-server.txt](https://github.com/user-attachments/files/15970810/crash-2024-06-25_14.41.47-server.txt)

**Comment by BeansGalaxy** [comment]
Oops, I was using a client only class on the server and the server couldn't find it. I'll get a fix out later today

**Comment by BeansGalaxy** [comment]
Solved in 20.1-2.0.2 ;)
