### ISSUE TITLE
There is a crash when you open any container 

### ISSUE THREAD

**Issue by Bitcode1134** [BeansGalaxy/Beans-Backpacks-2#173]
the error says “ The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke
*com.beansgalaxy.backpacks.data.Traits.getMaxStacks()* because
the return value of
*com.beansgalaxy.backpacks.data.Traits.get(String) is mull
Exit Code: -1 “ can you fix this. It happens whenever my friend opens their inventory or any kind of chest.

**Comment by BeansGalaxy** [comment]
Do you have the full log and does your game or the server shut down?

**Comment by Bitcode1134** [comment]
Just their game shut down and no I do not have the full log

**Comment by BeansGalaxy** [comment]
and is everyone all using v20.1-2.0.1?

**Comment by Bitcode1134** [comment]
Yes

**Comment by BeansGalaxy** [comment]
Does only crash for your friend or does any who opens the chest crash?

**Comment by Bitcode1134** [comment]
Only my friend.

**Comment by BeansGalaxy** [comment]
/ban {your friend's username} would fix it...

**Comment by Bitcode1134** [comment]
The problem is it’s not my server.

**Comment by BeansGalaxy** [comment]
I'm just kidding that would only cause irl problems. I think there might be an issue with the server side of the mod sending the data for the backpacks to their player. Are you on fabric or forge?

**Comment by Bitcode1134** [comment]
It’s on fabric

**Comment by BeansGalaxy** [comment]
So while going through the code `com.beansgalaxy.backpacks.data.Traits.get(String)` could only be `null` if the config wasn't sent over correctly. Now it defaults to the Iron backpacks if it runs into any issues and hopefully will work. I'm uploading v20.1-2.0.2 now and the server shouldn't need to update for it to work

**Comment by Bitcode1134** [comment]
Ok thx

**Comment by BeansGalaxy** [comment]
20.1-2.0.2 is out now. I also ran into a bug where the backpack would appear empty after placing it and opening it's menu. Somehow that took 4 hours but the server might need an update to fix these issues.
