### ISSUE TITLE
Duplication bug when breaking Extended Drawers with a backpack equipped

### ISSUE THREAD

**Issue by ThatSmartGuy21** [BeansGalaxy/Beans-Backpacks-2#19]
Loader: Fabric
MC Version: 1.20.1

Mods:
Fabric API - 0.91.0+1.20.1
Beans Backpacks - 0.7-v2
Extended Drawers - 2.1.1+mc.1.20.1

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/88632676/10d59e57-e5bc-46ac-b95a-f5f924b3f442

When I have a backpack equipped and I pick up one drawer, it works fine. But, when I pick up another drawer, it stacks with the first one, voiding the contents of the second drawer and duplicating those of the first.

**Comment by BeansGalaxy** [comment]
Oops... I was only checking if you picked up the same Item regardless of the nbt. I'll have to fix this in the next update

**Comment by BeansGalaxy** [comment]
Fixed in v2-0.8 for 1.20.2. Will port changes to 1.20.1 soon.
