### ISSUE TITLE
Lost all items when seeing credits (after Ender Dragon).

### ISSUE THREAD

**Issue by NatePlays95** [BeansGalaxy/Beans-Backpacks-2#2]
I had some 20 different items on it, from the dungeon before the end. Still had them in the End.
But when I jumped through the portal after killing the dragon and saw credits, poof, all gone.

The bug happens every time I jump through it back to spawn. Replicated it with worthless items.

version 0.1.1 for 1.20.1

**Comment by BeansGalaxy** [comment]
Fixed in v1.0. Very sorry about that....
