### ISSUE TITLE
No backpack slot with recent version (20.1 - 0.2-v2)

### ISSUE THREAD

**Issue by Tenuuu** [BeansGalaxy/Beans-Backpacks-2#24]
Title. No slot given but backpack can still be equipped
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/93273736/cf060fe6-fc47-4f6e-98ed-9e565ea52a30)

Latest Log:
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13986129/latest.log)

**Comment by BeansGalaxy** [comment]
yeahh oops... Broke it while adding trinkets/curios support. You can still pickup/place the backpack with the hotkey but I'm uploading a fix for 1.20.1 right now. 1.20.2 will be up in >1 hour

**Comment by BeansGalaxy** [comment]
Both 20.1 & 20.2 versions are up on modrinth and forge :)
