### ISSUE TITLE
Functionality for Button 4/Button 5

### ISSUE THREAD

**Issue by avilonlegends** [BeansGalaxy/Beans-Backpacks-2#25]
Hi there! First of all, really cool backpack-mod!

I wanted to ask if you could potentially add functionality for Buttons 4 and Button 5, which aren't present on a keyboard, but would be on a gaming mouse with additional buttons. For those who have their sprint-keybind on one of these mouse-buttons, instead of a keyboard-button.

For now, for example placing the backpack on the ground or clicking items in the inventory to move them quickly to the backpack appears to work just fine for keyboard-buttons, but apparently not if sprinting is keybound to such an additional mouse-button.

Thank you!

**Comment by BeansGalaxy** [comment]
Thats a good Idea. I would have to do some rewriting of the code in order to handle that though, I'll look into it. I think if you re-bind it to something still on the keyboard it should still need a right click.

**Comment by avilonlegends** [comment]
Thank you for your response!
Yeah, with a keyboard-keybind, it does need the right-click to function. But when binding sprint to for example Button 4 and pressing Button 4 + Click, nothing happens, since the functionality hasn't been implemented yet.

I have changed my sprint-keybind to a button on the keyboard for the time being.

**Comment by BeansGalaxy** [comment]
Your wish has been granted in 20.1-0.5-v2! When bound to sprint you cant place backpacks on top of one another. I don't think this is a big issue though since having 2 backpacks and being bound to sprint in pretty niche.
