### ISSUE TITLE
The mod does not want to work with the Curios API

### ISSUE THREAD

**Issue by DrBoom31** [BeansGalaxy/Beans-Backpacks-2#27]
Incorrect operation with the Curios API mod starts and works well, but if you use additional slots of the Curios API mod (1), the game crashes immediately. I tried it on several versions (2), but nothing has changed.

![1](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/157141530/a4d31f9d-93a6-44e3-af6a-352e5d7d01c3)

![2](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/157141530/6b762c4c-b4d9-470d-bf73-4951cd925f01)

[crash-2024-01-19_23.16.13-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13991750/crash-2024-01-19_23.16.13-client.txt)

**Comment by BeansGalaxy** [comment]
oops, I never accounted for there being more slots in the inventory when I wrote the code that's causing the crash. Easy fix.

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.4-v2 & 20.2-0.10-v2
