### ISSUE TITLE
2x2 Crafting output is treated as a proxy for the backpack slot (1.20.1, forge 47.1.3, mod version 0.4 v2)

### ISSUE THREAD

**Issue by PaperfishStudios** [BeansGalaxy/Beans-Backpacks-2#28]
Attempting to craft something in the player inventory seems to not allow the player to take crafting results out. When wearing a backpack it appears that the output slot is treated as a second copy of the backpack, letting you take items out and put them in the backpack
I was able to reproduce this bug on a fresh install of forge with no mods installed except Beans Backpacks

**Comment by BeansGalaxy** [comment]
A -1 was 0 and in the inventory the crafting recipe output is slot 0. Easy mistake, this'll be fixed in 20.1-0.5-v2 and 20.2-0.11-v2.
