### ISSUE TITLE
Backpacks dupe themselves very easily

### ISSUE THREAD

**Issue by fluffyxox** [BeansGalaxy/Beans-Backpacks-2#29]
Version 20.1-0.4-v2 fabric
Dying with a backpack in trinket slot both places the backpack on the ground, and drops one as an item.

In creative, equipping a backpack to trinket slot, unequipping and reequipping it will duplicate itself into a different available trinket slot. These duplicates place them in any and all slots. Mods adding trinket slots installed are Things, Supplementaries, and Cosmetic Armor.

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/121355849/ca6ad0e9-89c0-4f14-b963-68f8e3b4e3da

**Comment by fluffyxox** [comment]
Further information about the dying dupe method; it occurs with raw vanilla item splatter, no grave required. (just read the death dupe related to gravemod post and thought to clarify)
Also just tested on a raw profile, just this mod and fabric API. Both issues are specifically trinket slot related, death dupe not replicable with the pseudo slot added by this mod.

**Comment by BeansGalaxy** [comment]
Dying with a backpack was a problem in Curios and Trinkets and is now fixed in 20.1-0.5-v2. As for the creative bug, I re-wrote how I access the Curios/Trinkets slot so that it will always check and set to the 1st back slot.
