### ISSUE TITLE
my game crashes

### ISSUE THREAD

**Issue by damikdevil** [BeansGalaxy/Beans-Backpacks-2#30]
[crash-2024-01-21_21.45.50-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14001896/crash-2024-01-21_21.45.50-client.txt)
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14001897/latest.log)

**Comment by BeansGalaxy** [comment]
I've been getting this crash with a few different mods. This should be fixed since I am now using the mod loader's events instead of a mixin inject to register new player render layers.
