### ISSUE TITLE
Loosing backpack on death (w/ keep inventory)

### ISSUE THREAD

**Issue by 5antos** [BeansGalaxy/Beans-Backpacks-2#31]
As of version 20.1 - 0.4-v2, for fabric, if you have keep inventory enabled and die, you keep a copy of the backpack you were wearing in your inventory but the backpack with the items inside stays in your death spot.

I believe the correct behaviour should be that the backpack would be kept in its dedicated slot with the items inside it and should not be dropped on the death spot.

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.5-v2 :)
