### ISSUE TITLE
BeansBackpacks is incompatible with ModernFix's Dynamic Resources Feature

### ISSUE THREAD

**Issue by TofuToons** [BeansGalaxy/Beans-Backpacks-2#33]
Crash on startup with Beans Backpacks, ModernFix, and its Dynamic Resources Feature Enabled

Crash Report:
https://pastebin.com/dsAqe2UP
Log:
https://pastebin.com/s7bv7p6n

BeansBackpacks-fabric-1.20.1-0.1-v2.jar
modernfix-fabric-5.12.1+mc1.20.1.jar
Fabric 0.15.6
Minecraft 1.20.1

**Comment by BeansGalaxy** [comment]
modern fix and I are both fighting to redirect the same method. I could choose a different method, but I've already done that to solve another incompatibility. Currently looking into a safe way to inject my code without this issue popping up again.

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.6-v2 :)
