### ISSUE TITLE
Crash w/ Curios

### ISSUE THREAD

**Issue by WenXin20** [BeansGalaxy/Beans-Backpacks-2#34]
Minecraft v1.20.1

When unequipping an item from the curios slot, I got this crash
[Crash Report](https://gist.github.com/WenXin20/d7baa0ef31a295befdb46cebd58fb488)

**Comment by BeansGalaxy** [comment]
Fixed a while ago so instead I'm deleting the link to the old repository. Curios/Trinkets should be stable now
