### ISSUE TITLE
Bugged Tooltips

### ISSUE THREAD

**Issue by BookerCatch** [BeansGalaxy/Beans-Backpacks-2#35]
1. Drop a backpack containing items by pressing CTRL+Right-Click in the world on a block.
2. Press CTRL+Right-Click on the backpack to pick it up.
3. Inspect the backpack in its inventory slot; the tooltip will not display its contents.

Alternatively, if you interact with the backpack while it's on the ground and *then* you pick it up, the tooltip will properly display the contents.

**Comment by BeansGalaxy** [comment]
This was posted in the wrong repo and since I've re-written most of that code, so I'm marking this as complete
