### ISSUE TITLE
Infinite backpack duplication glitch.

### ISSUE THREAD

**Issue by Lcannine** [BeansGalaxy/Beans-Backpacks-2#36]
Dying while the backpack is in your inventory causes you to drop it but also keep it in the inventory upon death, meaning you can infinitely generate new backpacks as long as its in the backpack slot by just dying.

**Comment by BeansGalaxy** [comment]
Missed this since this was in the repo for the old version, but this has been fixed and is now working in properly in 0.5-v2. (Still broken in 1.20.2-0.10-v2 if curios/trinkets is installed but port coming soon)
