### ISSUE TITLE
beans backpacks causes a crash when another mod adds curios

### ISSUE THREAD

**Issue by PaperfishStudios** [BeansGalaxy/Beans-Backpacks-2#37]
tested in 1.20.1 with beans backpacks 0.6-v2, forge 47.1.3 and curios 5.5.0

i tried this independently with supplementaries (quiver and key are both curios) & gigaherz' Tool Belt v1.20.0 (the toolbelt itself is a curio)

here is the log from testing w/ tool belt: 
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14046658/latest.log)

if this cannot be fixed perhaps there could also be a config option to disable the curios backpack slot in favor of your own backpack slot (which i think works quite well for how the backpacks function here and i personally prefer this). it wouldn't fix the problem but might still allow people to work around it

**Comment by BeansGalaxy** [comment]
I just made a simple mistake in the code, literally one character caused this. This'll be fixed in 20.1-0.7-v2 & 20.2-0.8-v2. Probably will be released tmrw night.

**Comment by BeansGalaxy** [comment]
Posted 20.1-0.7-v2 & 20.2-12-v2 with the fix. It shouldn't crash when you're just using curios.
