### ISSUE TITLE
option to configure keybinds (specifically ctrl + rmb to place)

### ISSUE THREAD

**Issue by littlelakehouse** [BeansGalaxy/Beans-Backpacks-2#38]
coud not stress enough how many times we lost our backpack because of the ctrl + rmb to place. would be extremely helpful if there is an option to change the keybind for it. we love the mod btw!

**Comment by littlelakehouse** [comment]
ok just reread the mod description. can you tell us where to find the settings we already tried controls > keybinds but we couldnt find it there.

**Comment by BeansGalaxy** [comment]
It should be with the controls to place a block, pick block and attack. Let me know if you just missed it because I could see how players would expect its own category.

**Comment by BeansGalaxy** [comment]
In 20.1-0.7-v2 & 20.2-0.12-v2 the key is moved to it's own category in the keybind menu. After thinking about it, everyone expects modded keybinds to have their own category.
