### ISSUE TITLE
so umm it says Fabric Loader it has to be version 1.14.23 or Later, how do i fix this Beans backpack mod

### ISSUE THREAD

**Issue by Hrrfee** [BeansGalaxy/Beans-Backpacks-2#4]
Replace mod 'Fabric Loader' (fabricloader) 0.14.21 with version 0.14.23 or later.

Mod 'Beans Backpacks' (beansbackpacks) 1.0-1.20.1 requires version 0.14.23 or later of mod 'Fabric Loader'<br>(fabricloader), but only the wrong version is present: 0.14.21!

**Comment by BeansGalaxy** [comment]
You probably just have an older version of fabric installed to the minecraft launcher. Re-download the newest version of fabric and see if that works.
