### ISSUE TITLE
Blue Skies' Trims compatibility issue

### ISSUE THREAD

**Issue by Jous4n** [BeansGalaxy/Beans-Backpacks-2#41]
Blue Skies' adds 4 templates but you only get the missing textures when merging them with the backpacks.
![missing textures beans backpack](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/118950641/26b52eda-8b2d-4c77-9088-be52bd515af1)

**Comment by BeansGalaxy** [comment]
I'll look into adding those.

**Comment by Jous4n** [comment]
Thank you.

**Comment by BeansGalaxy** [comment]
Finally added textures in the coming update 20.1-0.20-v2 :)

**Comment by Jous4n** [comment]
> Finally added textures in the coming update 20.1-0.20-v2 :)

OMG THANK YOU. Sorry for not answering in time T_T

**Comment by BeansGalaxy** [comment]
No problem! Sorry for not answering in time ;)
