### ISSUE TITLE
Fabric 1.20.1 Server doenst start

### ISSUE THREAD

**Issue by pewblaze** [BeansGalaxy/Beans-Backpacks-2#43]
Hi client side works fine, but the server wont start with the mod :/
Im using Fabric 1.20.1 

latest.log:
https://gist.github.com/pewblaze/a4388b3402689bc4a3a894c52ebf45cb

**Comment by JAYDEMITE** [comment]
I appear to have the same issue https://mclo.gs/JC4z56Y

**Comment by gluzzie** [comment]
same but it happens on forge

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.10-v2 & 20.2-0.13-v2
