### ISSUE TITLE
(Fabric 1.20.1) Critical Compatibility issue with Trinkets

### ISSUE THREAD

**Issue by Pearilous** [BeansGalaxy/Beans-Backpacks-2#47]
Beans Backpacks 0.8-v2 for fabric has a bug where placing a backpack in a trinket slot (Trinkets 3.7.1) will duplicate the backpack into every trinket slot, making the mod unusable in most modpacks.

To recreate this bug:
Load a fabric 1.20.1 instance with Trinkets 3.7.1 and Beans Backpacks 0.8-v2.

Open a world and obtain a backpack.

Put the backpack in the "Back" Trinket slot.

Attempt to remove the backpack and replace it.

**Comment by Pearilous** [comment]
I should note that this issue was breifly posted as a regular bug and not a Compatibility issue. My bad.

**Comment by JAYDEMITE** [comment]
This might just be a creative mode thing, try this in survival

**Comment by Pearilous** [comment]
Good news, i tested it in survival and it turns out, it IS only an issue in creative. 
I tested on the version i listed in the original post (0.8-v2) AND the most recent version as of writing (0.10-v2) and it only duplicated the backpack in creative. Survival backpacks function as intended.

Both versions were tested with Trinkets 3.7.1 on Fabric 1.20.1

**Comment by BeansGalaxy** [comment]
Yeah sorry... I'm just completely ignoring using backpacks while in creative mode. It's kinda annoying downloading a mod and that mod doesn't work in creative so you can't play around with anything before you start a survival world but the creative inventory is a ***completely*** different inventory than the survival one so it makes de-bugging and coding faster to ignore it for now. 

I'll add it to my list of to-dos but honestly it'll be at the bottom of the list.
