### ISSUE TITLE
Texture Error on Fabric 1.20.1

### ISSUE THREAD

**Issue by HazelsInferno** [BeansGalaxy/Beans-Backpacks-2#50]
I don't know why this is happening, tried disabling (almost) every single mod I have on my modpack and it didn't change anything. I'm using Fabric 1.20.1, the 0.10v2 version of the mod.
My list of mods is here:

	- advancementscreenshot 4.7
	- alternate-current 1.7.0
	- animatica 0.6+1.20
	- aquatictorches 1.0.1
	- architectury 9.1.13
	- azurelib 2.0.20
	- balm-fabric 7.2.1
	- beansbackpacks 0.10-v2
	- betterbeds 1.3.0
	- betterchunkloading 1.20.1-3.3
	- bettertridents 8.0.1
	- bettertrims 2.2.3
	- boatiview 0.0.5
	- bobby 5.0.1
	- bookshelf 20.1.9
	- bridgingmod 2.2.1+1.20.1
	- c2me 0.2.0+alpha.11.3
	- cakechomps 6.1.1+1.20.1
	- calmdowndog 1.1.0
	- cherishedworlds 6.1.5+1.20.1
	- chunksending 1.20.1-2.8
	- citresewn 1.1.3+1.20
	- cloth-config 11.1.118
	- collective 7.30
	- companion 5.1.0
	- completeconfig 2.5.0
	- connectivity 1.20.1-4.9
	- controlling 12.0.2
	- crafter 1.0.1-1.20.1
	- crafttweaker 14.0.32
	- cristellib 1.1.5
	- cupboard 1.20.1-2.3
	- cyclepaintings 3.5
	- dogslie 1.2.0
	- dynamic_fps 3.3.3
	- dynamicvillagertrades 1.3.1
	- emi 1.1.1+1.20.1+fabric
	- enchanting-system-overhaul 1.0.6
	- enchantmentdisabler 0.1.4
	- enhancedblockentities 0.9+1.20
	- entity_model_features 1.2.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2-mc1.20.1
	- exposure 1.3.1
	- fabric-api 0.91.0+1.20.1
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	- fabricloader 0.15.6
	- fastload 3.4.0
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- fletchery 0.1.0
	- flowerymooblooms 2.0.1
	- forgeconfigapiport 8.0.0
	- friendsandfoes 2.0.9
	- glowing-torchflower 1.0.0
	- grapplemod 1.20-v1.7
	- guiclock 4.4
	- guicompass 4.4
	- head_in_the_clouds 1.0.1
	- herdspanic 1.0.7
	- here-be-no-dragons 1.0.0
	- horsebuff 2.1.2
	- immediatelyfast 1.2.10+1.20.4
	- immersive_aircraft 0.7.1+1.20.1
	- impactfulweather 4.1.0
	- inventory-tabs 1.1.8+1.20
	- inventorymanagement 1.3.1
	- java 17
	- kaffees_dual_ride 1.1.0
	- keepmysoiltilled 2.2
	- keepsomeinventory 1.3.3
	- keepthatmusic 0.0.5
	- krypton 0.2.3
	- languagereload 1.5.10+1.20.1
	- lazydfu 0.1.3
	- libertyvillagers 2.0.0+fabric+1.20.1
	- lithium 0.11.2
	- llamasteeds 2023.4.9
	- logbegone 1.0.8
	- lootr 0.7.29.75
	- lovely_snails 1.1.3+1.20.1
	- make_bubbles_pop 0.2.0-fabric
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- mobcatalog 1.0.7+1.20.1
	- mobsonrails 1.0.0
	- modernfix 5.13.0+mc1.20.1
	- modify-camera-collision 1.0.0
	- modmenu 7.2.2
	- moonlight 1.20-2.9.12
	- morecreativetabs 1.2.1
	- moremobvariants 1.2.2
	- mr_beta_nether 1-V1
	- mr_dungeons_andtavernspillageroutpostrework 1.1
	- mr_reimagined_trims 1.0.3
	- muffins_slimegolem 1.1.2
	- namepain 1.5.3
	- necronomicon 1.4.2
	- nerb 0.3
	- netherite_nugget 1.6.1
	- nethermap 3.0.0-1.20.1
	- netherportalfix 13.0.1
	- no-repair-cost 1.0.0-fabric-1.20.1
	- no-resource-pack-warnings 1.3.0
	- nochatreports 1.20.1-v2.2.2
	- nostalgic_tweaks 2.0.0-Beta-8.4.1
	- ocelotfix 1.0.0
	- offlineskins 1.20.1-v1a-fabric
	- overweight_farming 1.20.1-2.0.3-fabric
	- pack_it_up 0.3.1+1.20.1
	- paxi 1.20-Fabric-4.0
	- pehkui 3.7.12+1.14.4-1.20.4
	- polytone 1.20-1.14.6
	- portfolio 1.20.1-1.3.5-fabric
	- potioncauldron 1.0.1+mc1.20
	- preferred-gamerules 1.0.0+1.19.4
	- puzzleslib 8.1.16
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	- runic_enchanting 1.1+1.20.1
	- saplanting 1.2.5
	- searchables 1.0.2
	- seasons 2.3+1.20
	- shifty-hotbar 1.1
	- sleep_tight 1.20-1.1.19
	- smoothchunk 1.20.1-3.5
	- sneaky 1.2
	- snowyleavesplus 0.1.9
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	- souper_secret_settings 1.0.8-mc1.20+
	- sparsestructures 2.1.2
	- spyglass_astronomy 1.0.8-mc1.20.1
	- starlight 1.1.2+fabric.dbc156f
	- straightenup 1.2.0
	- structureessentials 1.20.1-3.2
	- superflatworldnoslimes 3.2
	- t_and_t 1.12
	- tipsmod 12.0.4
	- trimmable_tools 1.0.4
	- unionized-villagers 1.0
	- villagersffh 0.5.1
	- weakerspiderwebs 3.4
	- wilderwild 2.3-Fabric+1.20.1
	- wither-skeleton-propagation 1.0.1
	- xercamusic fabric-1.20.1-1.0.1
	- xercapaint fabric-1.20.1-1.0.0
	- yet_another_config_lib_v3 3.2.1+1.20
	- youwereslain 1.0.0-1.20.x
	- ysns 1.0.5
	- yungsapi 1.20-Fabric-4.0.3

![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/140119516/52183f9d-a454-4fd3-8c53-8eb59feacde5)
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/140119516/546e1c27-fecd-41d5-98e7-0d4e10c37d41)

**Comment by BeansGalaxy** [comment]
Most likely an issue with Entity Textures Features or one of your optimization mods. This it just an educated guess since I can't easily test each mod you listed. It would help if you included a download to your `latest.log` and tried removing as many mods and you can while still having this issue before posting the mod list.

**Comment by BeansGalaxy** [comment]
Closing this issue since I have no further info and it seems like an issue with your personal mod pack. Feel free to add any additional info you've might've found.
