### ISSUE TITLE
Item model not loading while [unknown mod] installed

### ISSUE THREAD

**Issue by nitrogenfive** [BeansGalaxy/Beans-Backpacks-2#52]
<img width="1440" alt="Screenshot 2024-02-17 at 3 48 43 PM" src="https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/105533515/2e445591-ce08-4f50-a6a8-86d7010d8d10">
<img width="1440" alt="Screenshot 2024-02-17 at 3 48 34 PM" src="https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/105533515/6cdb9f55-b48c-4335-936e-aa2c0cabbc32">
<img width="1440" alt="Screenshot 2024-02-17 at 3 48 28 PM" src="https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/105533515/10cc49df-7214-46d4-8668-2fb8400d8e4f">

**Comment by BeansGalaxy** [comment]
Would you mind sending a link to the modpack, or try removing as many mods as you can while still replicating this error?

**Comment by BeansGalaxy** [comment]
Unsure how to diagnose this mod without any info on what version, what mods you're playing with, or what mod loader you're using. Closing this issue.
