### ISSUE TITLE
Making item names changeable in JSON in the lang folder

### ISSUE THREAD

**Issue by kingofssal** [BeansGalaxy/Beans-Backpacks-2#53]
Hello, I like this mod a simple and compact. However in this mod can't change backpack names JSON in lang folder. I hope be that for localization

**Comment by BeansGalaxy** [comment]
I'll definitely look into this, the way it currently handles backpack names makes it a bit tricky but doable.

**Comment by BeansGalaxy** [comment]
Added in 20.1-0.12-v2+ & 20.2-0.15-v2+ :)
