### ISSUE TITLE
the equipped backpack disappears when you dying

### ISSUE THREAD

**Issue by mxrcury666** [BeansGalaxy/Beans-Backpacks-2#59]
the equipped backpack disappears when you dying. if its not equipped everything is ok

**Comment by BeansGalaxy** [comment]
Fixed in version 20.2-0.13-v2 & 20.2-0.16-v2. Thank you!

**Comment by mxrcury666** [comment]
> Fixed in version 20.2-0.13-v2 & 20.2-0.16-v2. Thank you!

where i can download it?
