### ISSUE TITLE
Thank you for update

### ISSUE THREAD

**Issue by kingofssal** [BeansGalaxy/Beans-Backpacks-2#63]
Here is Korean translate file :)

[ko_kr.json](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14358981/ko_kr.json)

**Comment by BeansGalaxy** [comment]
Thank you!! I'll add this in an update soon!

**Comment by BeansGalaxy** [comment]
After you so kindly gifted me this translation file I went and added 20+ more lines. If you can update it I'll throw it into the mod honestly this time.

**Comment by BeansGalaxy** [comment]
Closing this issue but feel free to upload an updated translation anytime :)
