### ISSUE TITLE
Compatibility issue with Universal Graves

### ISSUE THREAD

**Issue by IAMSTRANGLO** [BeansGalaxy/Beans-Backpacks-2#66]
When a player dies and a grave is created the backpack will be placed inside the grave instead of on/nearby where the player died. The backpack will be in item form and as a result lose its contents.

Running:
Minecraft 1.20.1
Quilt Loader 0.24.0-beta.8
BeansBackpacks-fabric-1.20.1-0.13-v2
graves-3.0.1+1.20.1
trinkets-3.7.1

**Comment by BeansGalaxy** [comment]
Grave mods really don't like other mods trying to do stuff while a player is dying. I'll try to look into it but I've already moved my code to as early in the sequence of code as I can.

**Comment by BeansGalaxy** [comment]
Thanks for all the Versions/Info too. It helps a ton :))
