### ISSUE TITLE
This happens whe I look a backpack with Jade mod

### ISSUE THREAD

**Issue by Canuki** [BeansGalaxy/Beans-Backpacks-2#67]
![e](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/161278933/ffd72a67-2854-4ed0-a711-926414a9bd8c)

**Comment by BeansGalaxy** [comment]
It's because I don't have the name properly formatted, I thought it would only be a problem in creative or using commands but easy fix.

**Comment by Canuki** [comment]
Alright, thanks!

**Comment by BeansGalaxy** [comment]
Fixed in 20.1-0.16-v2 :)
