### ISSUE TITLE
Backpack loses entire inventory if placed and picked up.

### ISSUE THREAD

**Issue by Snarke1** [BeansGalaxy/Beans-Backpacks-2#73]
I placed down my backpack to clean it out in the middle of a cave after looking a bunch of stuff in an ancient city. Once I finished cleaning it I picked it back up with left shift and everything in the backpack literally just disappeared.

**Comment by BeansGalaxy** [comment]
Are you using the latest version? I thought I fixed this in <ins>20.1</ins>-0.16-v2

**Comment by Snarke1** [comment]
modrinth unfortunately didnt show me an update available until after it happened so no, i wasnt on the latest version. i didnt realize it until after i posted this though. sorry.

**Comment by BeansGalaxy** [comment]
phew... I thought I released a version for the fix and never fixed it. You had me scared for a second but no problem! Sorry about your items :(
