### ISSUE TITLE
[Request] Trinkets support

### ISSUE THREAD

**Issue by 3ncanis** [BeansGalaxy/Beans-Backpacks-2#74]
Hello, I love your backpacks and how they function, super immersive. I use the Trinkets (https://modrinth.com/mod/trinkets) mod and would love to be able to put your backpacks in the backpack slot. (So I guess an option to toggle between having the backpack slot you added with this mod or being able to remove that and just use the Trinkets backpack slot) Great mod and keep up the good work.

**Comment by BeansGalaxy** [comment]
Trinkets is already supported unless you mean always being able to see the backpack item. As far as I know my mod should detect when you have the trinkets mod installed, then replaces the Back Slot with a "Insert Slot" that always shows the last item placed into the backpack. Then you equip the backpack in curios'/trinkets' Back Slot

Let me know if this isn't working as expected. Glad to see you're enjoying the mod!! 😎

**Comment by 3ncanis** [comment]
Yep, my bad haha. I just tried it out and it works flawlessly with trinkets. Sorry!

**Comment by BeansGalaxy** [comment]
No problem, you had me worried for a second tho I thought it was broke lol
