### ISSUE TITLE
Modifying Blacklist

### ISSUE THREAD

**Issue by VitaminJake** [BeansGalaxy/Beans-Backpacks-2#75]
I understand how to create custom backpacks and all of that, but how do we modify the data for the backpacks from the mod? I want to add a blacklist entry for other modded items for the actual beansbackpacks and can't find a JSON or anything anywhere where the mod data is stored. How does it work?

**Comment by BeansGalaxy** [comment]
Idk if you've read this too but here's the [wiki page](https://github.com/BeansGalaxy/Beans-Backpacks-2/wiki/Configurations) and here's the [template data pack](https://github.com/BeansGalaxy/Beans-Backpacks-2/tree/20.1/assets/resources/Modify%20Data%20Template). **DO NOT** name the folder inside data `beansbackpacks`. You can keep it as template or even name it `minecraft` and it'll work.

1. Download the data pack and inside you'll find `blacklist_items`.
2. add items by their IDs like `minecraft:dirt`
3. I have all shulkers disabled by default, if you want to remove that use `!` infront of items to force then to be enabled

Then just enable the datapack when you create the world or put it in the in a world's datapacks folder. Lmk if you need any more help.

**Comment by BeansGalaxy** [comment]
Btw I plan on re-writing how backpacks are added, if you've created any what did you think was lacking or needed to make it better?

**Comment by BeansGalaxy** [comment]
Closing this issue but feel free to still leave your thoughts
