### ISSUE TITLE
Crashing with "You're in Grave Danger" gravestone mod

### ISSUE THREAD

**Issue by 3ncanis** [BeansGalaxy/Beans-Backpacks-2#77]
It seems like when using the mod "You're in Grave Danger" https://modrinth.com/mod/yigd you lose the contents of your backpack, which is weird because in the config it seems to have specific support for your backpacks.

Edit: Actually I'm now crashing when I die wearing a backpack with items in it using Beans Backpacks and Youre in Grave Danger

[crash-2024-03-07_07.21.12-server.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14524524/crash-2024-03-07_07.21.12-server.txt)

**Comment by BeansGalaxy** [comment]
It looks like the creator of You're in Grave Danger added compatibility for my mod and in the latest update I broke it. From my testing if you don't have curios/trinkets installed, set `enableBeansBackpacksCompat` in yigd's config to false

**Comment by 3ncanis** [comment]
Oh i see, is there a fix if you do use trinkets?

**Comment by BeansGalaxy** [comment]
Me and the mod developer are working together to get a fix out soon :)

**Comment by 3ncanis** [comment]
Hi thank you so much for the update! I no longer crash at all when I have their config for beans backpacks disabled but unfortunately it seems I lose the items inside the backpack.

**Comment by BeansGalaxy** [comment]
Me and the dev from You're in Grave Danger are rolling out an update that should solve any future compatibilities. Look out for an update from both of us and re-enabling `enableBeansBackpacksCompat` should work again.

**Comment by BeansGalaxy** [comment]
Looks like the mod developer released a new version with the fixes. 2.0.0-beta.11 of You're in Grave Danger. It should be working with my mod again.
