### ISSUE TITLE
Mod seems VERY broken when using EMI

### ISSUE THREAD

**Issue by Killercrab432** [BeansGalaxy/Beans-Backpacks-2#78]
When using EMI to view the recipes for the bags not only does it just appear as a broken texture, none of the recipes even appear? like when pressing r so view recipes on the item literally nothing comes up except for the dying recipe for the default backpack
![2024-03-07_23 25 26](https://github.com/BeansGalaxy/BeansBackpacks/assets/105161116/c6b66b50-137d-4873-b594-0341f4a6fee2)
![2024-03-07_23 27 15](https://github.com/BeansGalaxy/BeansBackpacks/assets/105161116/a37b9f4c-e13b-4480-985c-60cd00721753)
![2024-03-07_23 24 30](https://github.com/BeansGalaxy/BeansBackpacks/assets/105161116/19300b17-8ee6-43bd-a890-97e2104405b3)

**Comment by Killercrab432** [comment]
looks like your latest update mostly fixed this issue, all recipes work correctly now aside from netherite and gold backpacks which just show the iron backpack recipe

**Comment by BeansGalaxy** [comment]
Closing this issue since all the bugs are ironed out and EMI dosen't support custom smithing recipes so I can't have netherite backpacks show their crafting recipe.
