### ISSUE TITLE
Curio crash

### ISSUE THREAD

**Issue by segic** [BeansGalaxy/Beans-Backpacks-2#81]
the mod causes a crash if installed alongside Create and Curios api, those are the only 3 mods i had installed. If i click on the curio head slot with this mod installed, it just outright crashes the game

MC 1.20.1, Forge 47.2.20

**Comment by BeansGalaxy** [comment]
Fixed a while ago, You reported this issue in the wrong repository that I rarely checked so sorry for missing this but I archived that repo and left a disclaimer in the ReadMe. Thanks for letting me know though :)
