### ISSUE TITLE
Winged Backpack does not use cape texture for elytra textures

### ISSUE THREAD

**Issue by MindFaer** [BeansGalaxy/Beans-Backpacks-2#82]
Forge 47.2.20, BeansBackpacks version 0.15 V2

This may be intentional as it matches the backpack, but just in case I wanted to bring it up.

**Comment by BeansGalaxy** [comment]
Simply re-coloring the special elytra textures looks bad. I could create special textures for all the variants but I know mods like optifine adds special capes to the game and I don't know how to handle those cases. For now Winged Backpacks just ignore if you have a cape but I'll add this to my to-do to re-consider later
