### ISSUE TITLE
Crash on Fabric 1.20.1 using 0.16-v2

### ISSUE THREAD

**Issue by wynter1888** [BeansGalaxy/Beans-Backpacks-2#84]
We are running a server with multiple people. My friend is unable to use any backpacks, as it instantly crashes his game. 

`[00:47:40] [Server thread/INFO]: Juju57292 lost connection: Internal Exception: java.util.ConcurrentModificationException: Async entity load`

This was the error we got in the server console. Not sure what exactly is causing it, as he was able to use backpacks before.

**Comment by BeansGalaxy** [comment]
Is everyone on the same version? Or attach a link to your crash.txt file or server log and I'll see if I can find anything else there.

**Comment by wynter1888** [comment]
I've decided to remove the mod entirely and unfortunately I had to roll back the server due to a duplication bug in the most recent version, so no logs are available. I am no longer interested in trying to solve this as it is incredibly frustrating and I just won't be using the mod anymore. Thank you for your time developing it and I hope to see it grow into a great experience in the future.

**Comment by BeansGalaxy** [comment]
Make sure you check it out when it's out of beta! Sorry about buggy behavior but I'm working of getting the last of it ironed out and thanks for checking my mod out ;)
