### ISSUE TITLE
Crash when observing enchanted book tooltip 

### ISSUE THREAD

**Issue by BoshaNova** [BeansGalaxy/Beans-Backpacks-2#88]
Fabric version: 0.92.0 + 1.20.1
Beans backpacks: 0.18 v2

While carrying an ender backpack, hovering over any enchanted books causes an immediate crash.

[crash-2024-03-14_15.05.48-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14608440/crash-2024-03-14_15.05.48-client.txt)

**Comment by BeansGalaxy** [comment]
I checked if a specific item could be converted into an ender backpack, then converted a different item by mistake. Fixed in 20.1-0.19-v2. Thanks for the report ;)
