### ISSUE TITLE
Issue with the mod "alex caves"

### ISSUE THREAD

**Issue by gluzzie** [BeansGalaxy/Beans-Backpacks-2#89]
There are missing textures for any backpack that gets a trim, the texture is just black and purple. the normal backpacks are fine but when I try to put a trim on them the texture doesn't work. this is only a problem with the "Alex Caves" mod.

**Comment by BeansGalaxy** [comment]
I'll look into adding them. For now, if you know how to make resource packs here's the link to the wiki about [Adding Modded Trims](https://github.com/BeansGalaxy/Beans-Backpacks-2/tree/20.1/common/src/main/resources/assets/minecraft/textures/trims/backpacks)

**Comment by YukiAhn** [comment]
Just wanted to add that the issue also occurs when using vanilla trims, not just Alex's Caves ones. But Alex's Caves is the mod that is causing this problem

**Comment by gluzzie** [comment]
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/110564511/8a93befc-4b8f-4476-9ed5-d2cad668222c)

**Comment by gluzzie** [comment]
its for every trim

**Comment by BeansGalaxy** [comment]
I added a way to easily add textures for backpacks a few updates ago and to load all the textures for the backpack trims, there needed to be a specific number of trims loaded and alex's caves pushed things around that caused none of my textures to load. 

Also I'll add a texture for the trim the mod adds too in version 20.1-0.20-v2

**Comment by BeansGalaxy** [comment]
0.20-v2 is live ;) thanks for the report
