### ISSUE TITLE
Crash with carpet mods [1.20.1]

### ISSUE THREAD

**Issue by DrLeonardo95** [BeansGalaxy/Beans-Backpacks-2#9]
Game is crashed after install carpet and Beabs-Backpacks mod.
**Log:** [carpet-beansBackpack.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/13840785/carpet-beansBackpack.txt)

**Info:**

- Minecraft - 1.20.1
- Fabric Loader - 0.15.3
- Mod version: - 1.0
- FabricAPI - 0.91.0

**Comment by BeansGalaxy** [comment]
It looks like both our mods are trying to redirect the same line of code when a player picks up an Item. Not sure of an easy fix but I'll look into it. Do you know the version of Carpet you're using so I can test?

**Comment by DrLeonardo95** [comment]
> It looks like both our mods are trying to redirect the same line of code when a player picks up an Item. Not sure of an easy fix but I'll look into it. Do you know the version of Carpet you're using so I can test?

**Carpet mod:** 1.4.112 
Client crash occurs when launching the game client

**Comment by BeansGalaxy** [comment]
Fixed in v1.1. Super simple too just had to look at it different.
