### ISSUE TITLE
Ender Backpack crash issue

### ISSUE THREAD

**Issue by bic060** [BeansGalaxy/Beans-Backpacks-2#90]
I'm on server Cursed Walking 1.20.1 v1.3 modpack with beansbackpack 20.1 0.18 v2.
I got constant crashing whenever I equipped ender backpack on my body, all remain backpacks work just fine.
[crash-2024-03-18_17.34.16-client.txt](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14634863/crash-2024-03-18_17.34.16-client.txt)

**Comment by Killercrab432** [comment]
https://pastebin.com/eDgj97pD seems like im getting the same issue

**Comment by bic060** [comment]
> https://pastebin.com/eDgj97pD seems like im getting the same issue

Are you on the same mod pack as mine?

**Comment by BeansGalaxy** [comment]
I made a mistake in the last update where I check if an item can be converted to a ender backpack then I convert a different item on accident. 20.1-0.19-v2 has this fixed, it should be out tomorrow or today.

**Comment by Killercrab432** [comment]
> > https://pastebin.com/eDgj97pD seems like im getting the same issue
> 
> Are you on the same mod pack as mine?

Nope im on my own modpack i made

**Comment by BeansGalaxy** [comment]
20.1-0.19-v2 is live! Thanks for being patient, I'll let the developer of Cursed Walking know to update my mod.
