### ISSUE TITLE
java.util.ConcurrentModificationException: Async entity load when using with Concurrent Chunk Management Engine

### ISSUE THREAD

**Issue by Mangraz** [BeansGalaxy/Beans-Backpacks-2#91]
In Singleplayer as well as Multiplayer, the client gets kicked with the error message "java.util.ConcurrentModificationException: Async entity load", when trying to place or pick up a backpack. [Here](https://mclo.gs/0KtDOnK) is the log with only these mods running.

**Comment by BeansGalaxy** [comment]
I couldnt recreate the issue but I assume it had something to do with creating an entity on the client. This should be fixed in version 20.1-0.19-v2. Feel free to open this issue up again if you continue to have this problem.
